<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="74280" started-at="2019-01-11T07:10:03Z" finished-at="2019-01-11T07:11:17Z">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:org.drc.vat.StepDefinitions.TestRunner@43aeb5e0]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Default test" duration-ms="74280" started-at="2019-01-11T07:10:03Z" finished-at="2019-01-11T07:11:17Z">
      <class name="org.drc.vat.StepDefinitions.TestRunner">
        <test-method status="PASS" signature="setUP_Mobilenop()[pri:0, instance:org.drc.vat.StepDefinitions.TestRunner@43aeb5e0]" name="setUP_Mobilenop" is-config="true" duration-ms="5541" started-at="2019-01-11T12:39:57Z" finished-at="2019-01-11T12:40:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP_Mobilenop -->
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:org.drc.vat.StepDefinitions.TestRunner@43aeb5e0]" name="setUpClass" is-config="true" duration-ms="447" started-at="2019-01-11T12:40:03Z" finished-at="2019-01-11T12:40:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:org.drc.vat.StepDefinitions.TestRunner@43aeb5e0]" name="feature" duration-ms="73163" started-at="2019-01-11T12:40:03Z" description="Runs Cucumber Feature" data-provider="features" finished-at="2019-01-11T12:41:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Account Adjustment Statement of Transaction TaxPayer Profile & Objection]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: expected [-307.68] but found [2.24]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [-307.68] but found [2.24]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [-307.68] but found [2.24]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at org.drc.vat.StepDefinitions.AccountAdjustmentStmtofTransac.user_selects_Charge_and_Enter_Amount_to_be_adjusted_VAT_Liability_LateFee_Penalty_Interest_should_be_non_editable(AccountAdjustmentStmtofTransac.java:361)
	at âœ½.Then user selects Charge"Credit" and Enter Amount to be adjusted VAT Liability"500"LateFee"0"Penalty"50000"Interest should be non-editable(features/42_AccountAdjustmentStmtofTransac.feature:33)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:org.drc.vat.StepDefinitions.TestRunner@43aeb5e0]" name="tearDownClass" is-config="true" duration-ms="557" started-at="2019-01-11T12:41:17Z" finished-at="2019-01-11T12:41:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.drc.vat.StepDefinitions.TestRunner@43aeb5e0]" name="tearDown" is-config="true" duration-ms="691" started-at="2019-01-11T12:41:17Z" finished-at="2019-01-11T12:41:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.drc.vat.StepDefinitions.TestRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
